/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-04-14 05:18:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import cart.*;

public final class DisplayCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("cart");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta name=\"GENERATOR\" content=\"Microsoft FrontPage 5.0\">\n");
      out.write("<meta name=\"ProgId\" content=\"FrontPage.Editor.Document\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1252\">\n");
      out.write("<title>My page title</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");

    Cart cart = (Cart) session.getAttribute("cart");
    Collection cartItems = cart.getCartItems();
    Iterator it = cartItems.iterator();

      out.write("\n");
      out.write("\n");
      out.write("<table width=\"100%\" height=\"100%\">\n");
      out.write("<tr>\n");
      out.write("<td width=\"100%\" height=\"20%\" bgcolor=\"blue\">&nbsp;</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td width=\"100%\" height=\"60%\" bgcolor=\"yellow\">\n");
      out.write("<form method=\"get\" action=\"/Shop/decision\">\n");
      out.write("<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\n");
      out.write("<caption>Your Cart</caption>\n");
      out.write("<tr>\n");
      out.write("    <th>Item Purchased</th>\n");
      out.write("    <th>Quantity</th>\n");
      out.write("    <th>Rate</th> \n");
      out.write("    <th>Remove</th>\n");
      out.write("</tr>\n");

    while(it.hasNext()) {
        CartItem cartItem = (CartItem) it.next();

      out.write("\n");
      out.write("<tr>\n");
      out.write("    <td>");
      out.print( cartItem.getItem().getDescription() );
      out.write("</td>\n");
      out.write("    <td align=\"center\">\n");
      out.write("        <input type=\"text\" name=\"T");
      out.print( cartItem.getCartItemId() );
      out.write("\" size=\"1\" value=\"");
      out.print( cartItem.getQuantity() );
      out.write("\">\n");
      out.write("    </td>\n");
      out.write("    <td>");
      out.print( cartItem.getItem().getPrice() );
      out.write("</td>\n");
      out.write("    <td align=\"center\"><input type=\"checkbox\" name=\"");
      out.print( cartItem.getCartItemId() );
      out.write("\" value=\"ON\"></td>\n");
      out.write("</tr>\n");

    }

      out.write("\n");
      out.write("<tr>\n");
      out.write("    <td colspan=\"2\">Total Amount</td>\n");
      out.write("    <td>");
      out.print( cart.getCartValue() );
      out.write("</td>\n");
      out.write("    <td>&nbsp;</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("    <td colspan=\"4\">\n");
      out.write("        <input type=\"submit\" value=\"Update Cart\" name=\"update\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("        <input type=\"submit\" value=\"Shop More\" name=\"shop\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("        <input type=\"submit\" value=\"Freeze Cart\" name=\"freeze\">\n");
      out.write("    </td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td width=\"100%\" height=\"20%\" bgcolor=\"blue\">&nbsp;</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<p>&nbsp;</p>\n");
      out.write("<p>&nbsp;</p>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
